version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.6
    - 9.0.7
    - 9.0.8
  - dependency-name: get-stdin
    versions:
    - 8.0.0
